name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Verificando o código do repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configurando a versão do Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'

      # Instalando dependências sem exigir um arquivo de lock
      - name: Install dependencies
        run: npm install --no-fund --no-audit

      # Checando tipos TypeScript
      - name: TypeScript Check
        run: npm run check

      # Rodando o build
      - name: Build the project
        run: npm run build

      # Executando testes
      - name: Run Tests
        run: npm test
